sudo: required
language: csharp
solution: TSPLIB.sln
dotnet: 2.1.403
mono: none

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.4

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

script:
  - dotnet build
  - dotnet test TSPLIB.Tests
