sudo: required
language: csharp
solution: TSPLIB.sln
dotnet: 2.1.403
mono: none

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.4

script:
  - dotnet build
  - dotnet test
