sudo: required
language: csharp
solution: TSPLIB.sln
dotnet: 2.1.403
mono: none

os:
  - linux
  - osx

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

before_script:
  - dotnet tool install fake-cli -g

script:
  - fake run build.fsx -t Test

jobs:
  include:
    - stage: publish
      name: "Submit Nuget Package"
      if: branch = master AND tag =~ /^v\d{1,3}\.\d{1,3}\.\d{1,3}$/
      os: linux
      dist: trusty
      env:
        - NUGET_API_KEY
      script:
        - fake run build.fsx -t Deploy-Nuget

