sudo: required
language: csharp
solution: TSPLIB.sln
dotnet: 2.1.403
mono: none

os:
  - linux
  - osx

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

script:
  - dotnet test TSPLIB.Tests

jobs:
  include:
    - stage: publish
      name: "Submit Nuget Package"
      if: branch = master AND tag =~ /v\d+\.\d+\.\d+/
      os: linux
      dist: trusty
      env:
        - VERSION_NUMBER
        - NUGET_API_KEY
      script:
        - dotnet pack -c Release -o ../build TSPLIB/TSPLIB.fsproj
        - dotnet nuget push build/* -s https://www.nuget.org -k ${NUGET_API_KEY}

